# Generated by Django 3.2.8 on 2021-10-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counter', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('true_owner', models.CharField(max_length=255, null=True)),
                ('first_sale', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
