# Generated by Django 3.2.8 on 2021-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarity',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
